##
# -- Redis --
##
redis:
  cpu_count: 2
  cpu_percent: 50
  image: docker.io/library/redis:alpine
  mem_limit: 128m
  networks:
    default:
      aliases:
      - cache
  restart: always
##
# -- MariaDB --
# Required for the control panel to work.
# Stores Server/User information
##
mariadb:
  image: docker.io/library/mariadb:10.6
  env_file: ./conf.d/mariadb.env
  networks:
    default:
      aliases:
      - mysql
  restart: always
  volumes:
  - ./data/mysql:/var/lib/mysql